name: Docker Image CI

on:
  push:
    branches: [ "docker" ]
  pull_request:
    branches: [ "docker" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag afda:latest
    - name: Export Image
      run: docker save afda:latest -o afda.tar
    - name: Upload Image
      uses: actions/upload-artifact@v5
      with:
          name: docker-image
          path: afda.tar
